### ISSUE TITLE
Tentang proyek

### ISSUE THREAD

**Issue by billalxcode** [yandinovriandi/WMH#3]
Halo kawan, gw tertarik nih untuk kontribusi dalam proyek ini. apakah proyek ini bisa dikembangkan lebih lanjut atau hanya sebatas pembelajaran saja? dan bagaimana nasib proyek ini untuk kedepan nya?

Jika memang ini merupakan proyek jangka panjang, tolong invite saya menjadi kontributor proyek ini. dan buatkan Projects nya. Terima kasih

**Comment by yandinovriandi** [comment]
ini untuk jangka panjang kak, selagi saya bisa akan terus di kembangkan dan bisa di pakai dan mungkin bermanfaat untuk orang banyak!

**Comment by yandinovriandi** [comment]
> tolong invite bang jadi kontributor, nnti abang bikin todo list jangka panjang dan fitur nya. Nnti ku coba kerjain task nya

sudah saya invite. iya saya bikin tasks nya

**Comment by billalxcode** [comment]
> > tolong invite bang jadi kontributor, nnti abang bikin todo list jangka panjang dan fitur nya. Nnti ku coba kerjain task nya
> 
> sudah saya invite. iya saya bikin tasks nya

sipp bang
